### ISSUE TITLE
"import fdgis" generates error

### ISSUE THREAD

**Issue by mstuyts** [FirstDraftGIS/fdgis-qgis#3]
In the file fdgis_dialog.py line 2 "import fdgis" generates an error.

**Comment by DanielJDufour** [comment]
Unfortunately, in the short term, this plugin has a few dependencies.  You will need to `pip install fdgis requests validators`.

* As a medium-term goal, I will work toward making it so this plugin doesn't have any dependencies.  See https://github.com/FirstDraftGIS/fdgis-qgis/issues/4

Thank you for your feedback!

**Comment by mstuyts** [comment]
Even after `pip install fdgis requests validators` I get the following error:


```Couldn't load plugin FirstDraftGIS due to an error when calling its classFactory() method 

ImportError: cannot import name alarm 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/michstuy/.qgis2/python/plugins\FirstDraftGIS\__init__.py", line 34, in classFactory
    from .firstdraftgis import FirstDraftGIS
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/michstuy/.qgis2/python/plugins\FirstDraftGIS\firstdraftgis.py", line 7, in 
    from fdgis_dialog import FileDialog, LinkDialog, TextDialog
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/michstuy/.qgis2/python/plugins\FirstDraftGIS\fdgis_dialog.py", line 2, in 
    import fdgis
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\fdgis\__init__.py", line 13, in 
    from timeout import Timeout
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\fdgis\timeout\__init__.py", line 2, in 
    from signal import alarm, SIGALRM, signal
ImportError: cannot import name alarm


Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.9 Las Palmas, 3a16a4e```

**Comment by DanielJDufour** [comment]
That's my bad.  The "signal" package doesn't have "alarm" on Windows (https://docs.python.org/2/library/signal.html).  I'll fix this ASAP.  Shouldn't take more than a day.

**Comment by DanielJDufour** [comment]
Fixed.  Run ```pip install -U fdgis``` to fix on your end.  You don't need to update the plugin itself.

Thanks again for the great feedback! :)

**Comment by mstuyts** [comment]
The error is gone.
